### PR TITLE
Add testing support

### PR DESCRIPTION
**Pull request by splitbrain**
This is a pull request inside my fork to get some feedback first before I apply it to https://github.com/GeSHi/geshi-1.0/pull/78

@cweiske as you can see I moved the actual checks out of contrib/langcheck.php into a new class LangCheck in tests. This of course duplicates code now, which we should avoid, so:

* we could say that langcheck is obsolete with a proper test suite in place and can be removed
* if you say langcheck is still useful:
  * is the ability to run it via web and command line important?
  * would it be okay to pull in a 3rd party dependency for easier command line interfacing (I would suggest my own php-cli library which has no additional dependencies)

When writing the dogfood test I noticed that GeSHi fails to highlight itself. It stops in the middle of it's own code. This is already broken in master (you can try via contrib/example.php), so my changes did not break it. For now I just commented out the assertion. But that should probably be fixed some day.

### CODE REVIEW

**Comment by cweiske** [comment]
I've actually added a travis branch already https://travis-ci.org/GeSHi/geshi-1.0

My current problem is that regex on PHP7 behave differently than on php5.

**Comment by cweiske** [comment]
I'm in favor of LangCheck.php that encapsulates the functionality.

**Comment by splitbrain** [comment]
Yeah that author et al regexps had a couple of problems on some files depending on the content in the comment. That's why I split it up into selecting the comment first, then use simpler regexps on that.

**Comment by splitbrain** [comment]
so in favor of LangCheck class means we can remove contrib/langcheck.php?

**Comment by cweiske** [comment]
but we still need a way to check a single lang file.

**Comment by splitbrain** [comment]
Okay, phpunit supports that through named data sets. See d7e68bf

**Pull request merged**
